name: PHP Composer

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Display PHP version
      run: php -v

    - name: Install dependencies
      uses: php-actions/composer@v2

    - name: Run style linter
      run: composer run-script style-lint

    - name: Run static analyzer
      run: composer run-script stan

    - name: Run test suite
      run: composer run-script test-ci
